class PlanetData:
    star_index: int
    planet_index: int
    name: str
    type: str
    type_id: int
    singularity: int
    singularity_str: list[str]
    pos_m: list[float] #m
    pos_ly: list[float] #LY
    seed: int
    lumino: float
    wind: float
    radius: float #AU
    liquid: int
    is_gas: bool
    dsp_level: int
    raw_dsp_degree: float
    enhance_dsp_degree: float
    obliquity: float #deg
    land_percent: float
    veins_point: list[int]
    veins_amount: list[int]
    gas_veins: list[float]
    moons: list[PlanetData]

class StarData:
    star_index: int
    name: str
    type: str
    type_id: int
    seed: int
    dyson_lumino: float
    dyson_radius: float #m
    distance: float #LY
    pos_m: list[float] #m
    pos_ly: list[float] #LY
    planets: list[PlanetData]
    veins_point: list[int]
    veins_amount: list[int]
    gas_veins: list[float]
    liquid: list[int]

class GalaxyData:
    seed_id: int
    star_num: int
    resource_index: int
    resource_rate: float
    stars: list[StarData]
    veins_point: list[int]
    veins_amount: list[int]
    gas_veins: list[float]
    liquid: list[int]

class PlanetCondition:
    satisfy_num: int = 1
    dsp_level: int = 0
    type: int = 0
    singularity: int = 0
    need_veins: int = 0
    veins_point: list[int] = [0] * 14
    veins_amount: list[int] = [0] * 14
    moons: list[PlanetCondition] = []

class StarCondition:
    satisfy_num: int = 1
    type: int = 0
    distance: float = 1000.0
    dyson_lumino: float = 0.0
    need_veins: int = 0
    veins_point: list[int] = [0] * 14
    veins_amount: list[int] = [0] * 14
    planets: list[PlanetCondition] = []

class BondCondition:
    satisfy_num: int = 0
    distance: float = 1000.0 #LY
    con1: PlanetCondition|StarCondition = PlanetCondition()
    con2: PlanetCondition|StarCondition = PlanetCondition()

class GalaxyCondition:
    valid_state: bool = True
    need_veins: int = 0
    veins_point: list[int] = [0] * 14
    veins_amount: list[int] = [0] * 14
    stars: list[StarCondition] = []
    planets: list[PlanetCondition] = []
    bonds: list[BondCondition] = []

class Seed:
    seed_id: int
    star_num: int
    resource_index: int

class SeedManager:
    def __init__(self): ...
    def add_seed(self, seed:int, star_num:int) -> None: ...
    def del_seed(self, seed:int, star_num:int) -> None: ...
    def clear(self) -> None: ...
    def reset_index(self) -> None: ...
    def get_seeds_count(self) -> int: ...
    def get_seeds(self, batch_size:int) -> list[Seed]: ...

class GetDataQueue:
    def __init__(self, max_cache:int): ...
    def add_task(self, seed: Seed, thread_num: int) -> None: ...
    def shutdown(self) -> None: ...
    def get_results(self) -> list[GalaxyData]: ...

class GetDataManager:
    def __init__(self, max_thread:int, quick:bool, max_cache:int): ...
    def add_task(self, seed: Seed) -> None: ...
    def shutdown(self) -> None: ...
    def get_results(self) -> list[GalaxyData]: ...

class CheckPreciseManager:
    def __init__(self, seed_manager:SeedManager, resource_index:int, galaxy_condition:dict, quick:bool, max_thread:int): ...
    def run(self) -> None: ...
    def is_running(self) -> bool: ...
    def start_wait(self) -> None: ...
    def end_wait(self) -> None: ...
    def shutdown(self) -> None: ...
    def get_task_num(self) -> int: ...
    def get_task_progress(self) -> int: ...
    def get_result_num(self) -> int: ...
    def get_last_result(self) -> Seed: ...
    def get_results(self) -> list[Seed]: ...

class CheckBatchManager:
    def __init__(self, start_seed:int, end_seed:int, start_star_num:int, end_star_num:int, resource_index:int, galaxy_condition:dict, quick:bool, max_thread:int): ...
    def run(self) -> None: ...
    def is_running(self) -> bool: ...
    def start_wait(self) -> None: ...
    def end_wait(self) -> None: ...
    def shutdown(self) -> None: ...
    def get_task_num(self) -> int: ...
    def get_task_progress(self) -> int: ...
    def get_result_num(self) -> int: ...
    def get_last_result(self) -> Seed: ...
    def get_results(self) -> list[Seed]: ...

class GPUBenchmark:
    def __init__(self, max_thread: int, heavy: bool): ...
    def run(self) -> None: ...
    def shutdown(self) -> None: ...
    def reset(self) -> None: ...
    def get_speed(self) -> float: ...

def do_init_c() -> None: ...
def set_device_id_c(device_id:int) -> bool: ...
def get_device_id_c() -> int: ...
def set_local_size_c(local_size:int) -> None: ...
def get_local_size_c() -> int: ...
def get_device_info_c() -> list[str]: ...
def set_gpu_max_worker_c(max_worker: int) -> None: ...
def get_gpu_max_worker_c() -> int: ...
def galaxy_condition_to_struct(galaxy_condition:dict) -> GalaxyCondition: ...
def get_galaxy_data_c(seed:Seed, quick:bool) -> GalaxyData: ...
def get_galaxy_data_fast_c(seed:Seed, quick:bool, gen_planet_num: int = -1, vein_mask: int = 0x3FFF) -> GalaxyData: ...
def check_batch_c(start_seed:int, end_seed:int, start_star_num:int, end_star_num:int, resource_index:int, galaxy_condition:dict, quick: bool) -> list[str]: ...
